# Generated by Django 5.2.7 on 2025-10-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'posts'},
        ),
    ]
